// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDns-BKF3eQ_GK7anQPrKyqbVNFklelxK8',
    appId: '1:50839688997:web:0d1d7676949e08e9a2eccc',
    messagingSenderId: '50839688997',
    projectId: 'ahmadimranclothing',
    authDomain: 'ahmadimranclothing.firebaseapp.com',
    storageBucket: 'ahmadimranclothing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVT5qUOplvgcNO5yB5clpql6iX1gFuXeE',
    appId: '1:50839688997:android:c9186c9a3733c9caa2eccc',
    messagingSenderId: '50839688997',
    projectId: 'ahmadimranclothing',
    storageBucket: 'ahmadimranclothing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzc-ISgmAcM6W9e54hPN99cZVXd1dRCdQ',
    appId: '1:50839688997:ios:52fd2527d9f25eb9a2eccc',
    messagingSenderId: '50839688997',
    projectId: 'ahmadimranclothing',
    storageBucket: 'ahmadimranclothing.firebasestorage.app',
    iosBundleId: 'com.example.ahmadimranclothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzc-ISgmAcM6W9e54hPN99cZVXd1dRCdQ',
    appId: '1:50839688997:ios:52fd2527d9f25eb9a2eccc',
    messagingSenderId: '50839688997',
    projectId: 'ahmadimranclothing',
    storageBucket: 'ahmadimranclothing.firebasestorage.app',
    iosBundleId: 'com.example.ahmadimranclothing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDns-BKF3eQ_GK7anQPrKyqbVNFklelxK8',
    appId: '1:50839688997:web:d7712340fe8e9f69a2eccc',
    messagingSenderId: '50839688997',
    projectId: 'ahmadimranclothing',
    authDomain: 'ahmadimranclothing.firebaseapp.com',
    storageBucket: 'ahmadimranclothing.firebasestorage.app',
  );

}